# ========== Server ==========
server.port=8080
spring.application.name=TKPMHDT0.1

# ========== Database (SQL Server) ==========
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TKPMHDT1;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ========== JPA / Hibernate ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.connection.CharSet=utf8
spring.jpa.properties.hibernate.connection.characterEncoding=utf8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.open-in-view=true

# ========== Thymeleaf ==========
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ========== Jackson / JSON ==========
spring.jackson.serialization.fail-on-empty-beans=false

# ========== Mail (SMTP) ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=147258369het@gmail.com
spring.mail.password=zcnabdanqqrqqqwe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email hiển thị ở trường From
app.mail.from=147258369het@gmail.com



